apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app-svc
  namespace: {{ .Release.Namespace }}
  labels:
      app: python-app
spec:
  type: {{ .Values.service.type }}
  selector:
    app: python-app
  ports:
    - protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}