apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-nginx-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: "nginx.shay.com"
    http:
      paths:
      - pathType: {{ .Values.ingress.pathType }}
        path: /
        backend:
          service:
            name: {{ .Release.Name }}-nginx-svc
            port:
              number: {{ .Values.service.port }}
  - host: "app.shay.com"
    http:
      paths:
      - pathType: {{ .Values.ingress.pathType }}
        path: /
        backend:
          service:
            name: {{ .Release.Name }}-app-svc
            port:
              number: {{ .Values.service.port }}
