apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: nginx
  ports:
    - protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port }}
      targetPort:  {{ .Values.service.targetPort }}